replicaCount: 1

app:
  name: "default-service"

image:
  registry: "bankingappregistrydev.azurecr.io"
  tag: "latest" 
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8080 

database:
  host: ""
  name: ""

ingress:
  enabled: false
  host: ""